-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.candidaties
(
    user_id integer NOT NULL,
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    identity_number character varying(11) NOT NULL,
    birth_date date NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.companies
(
    user_id integer NOT NULL,
    company_name character varying(200) NOT NULL,
    web_address character varying(50) NOT NULL,
    phone_number character varying(11) NOT NULL,
    is_activated bit(1) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.company_activation_codes
(
    id integer NOT NULL,
    company_user_id integer NOT NULL,
    activation_code character varying(30) NOT NULL,
    it_confirmed bit(1) NOT NULL,
    confirmed_date date,
    PRIMARY KEY (id)
);

CREATE TABLE public.company_activation_employees
(
    id integer NOT NULL,
    company_user_id integer NOT NULL,
    confirmed_employee_user_id integer,
    confirmed_date date,
    PRIMARY KEY (id)
);

CREATE TABLE public.employees
(
    user_id integer NOT NULL,
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_titles
(
    id integer NOT NULL,
    title character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(50) NOT NULL,
    password character varying(25) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.companies
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.company_activation_employees
    ADD FOREIGN KEY (company_user_id)
    REFERENCES public.companies (user_id)
    NOT VALID;


ALTER TABLE public.company_activation_employees
    ADD FOREIGN KEY (confirmed_employee_user_id)
    REFERENCES public.employees (user_id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;